version: '3.9'

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - '8000:8000'
    volumes:
      # sync the code directory to the container, so we no need to rebuild the image
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
